export const messages: Record<string, string> = {
    "2026-07-04":
        "Tjaaaa, ich hab mir irgendwie gedacht, das könnte doch eine ganz nette Idee sein, oder? Motiviert dich ja ein bisschen noch Hashis zu machen oder so. Und so ein bisschen von mir geschrieben hat dir ja auch bisher gefallen. Ich vermiss dich einfach jetzt schon, aber nicht sooo schlimm. Also schon aber ich freu mich halt immer dich wieder zu sehen. Ich liebe dich. Dein Basti ♥ ",
    "2026-07-05": `Wooow, einfach Sonntag! Ich hab heute Prüfung mit der Lena, wird sicher toll sein. Ist ja eh nur Goldstar also schaff ich ganz bestimmt. Ich würde aber soooo viel lieber mit dir tanzen. Hoffe du hast aber trotzdem ganz viel Spaß und so, warst eeeecht schon lang nicht mehr im BuDo. Und richt mal liebe Grüße an die Emma aus. Hab dich liiieb. Dein Basti ♥ \n\n PS: Der Wechsel zwischen Nachrichten ist immer so um 2 Uhr Nachts damit da bissi weniger Stress ist`,
    "2026-07-06": `Haaaallloooooo. Ich bin im Auto. Also war. Oder werde sein? Keine Ahnung wann du das hier machst. Jetzt bin ich einfach noch weiter weg von dir 😭😭 Aber immerhin bisschen Strand. Also ich mag Strand ja nicht. Viel zu langweilig. Aber kann ja manchmal okay sein oder? Boaaaa, gestern war toll. Also die Prüfung war ganz okay so, aber dann am Donauinselfest. Einfach mit der Detti zusammen war ur nett, einfach Ness voll cooooool. Hab ich sooo gern gehabt. Und auch einfach mit der Detti plaudern so. Bissi Leben leben oder so. Ach ich liebe dich. Dein Basti ♥ \n\n PS: Ich sollte wohl erwähnen, dass die Nachrichten immer nur an einem Tag da sind. Also wenn du was verpasst, dann ups. Und dass ich die irgendwie so nur ein paar Tage vorschreibe. Alsooo, wenn ich Mal nicht dazu komme oder so dann muss ich mir da was ausdenken um aufzuholen.`,
    "2026-07-07": `Tjaaa, heute ist wohl mein erster Tag Strand. Oder vielleicht war ich gestern auch schon. Keine Ahnung. Vermutlich liege ich eh gerade am Strand oder so. Lese ein Buch und genieße die Sonne. Aja, ich hab Bücher dabei. So zwei, wollte eigentlich so sechs nehmen aber das ist wohl übertrieben. Irgendsoeine Tribute von Pandora oder so ähnlich. Kennst du vielleicht, soll ja ganz okay sein. Hihi. Und so ein anderes Buch aus der Bücherei. Muss mal schauen ob das gut ist so, kenn ich nicht aber hat gut geklungen. Najaaa, ich liebe dich. Dein Basti ♥ `,
    "2026-07-08": `Bin mir noch nicht ganz sicher ob es schlau ist immer bissi vorzuschreiben. Hast ja am Montag gesehen was passiert wenn ich dann noch was dazu schreibe, wird dann bissi viel. Aber finds schon lustiger so. Zeigt ein bisschen was ich so vermute was passieren wird. Und kann ja so schreiben was ich wirklich mache. Also das ist ja auch vorgeschrieben. Heute war aber sicher auch toll. Vermiss dich aber seeeehr. Wäre so schön mit dir. Aber sehen uns ja eh bald wieder oder so. Hab dich liiieb. Dein Basti ♥`,
    "2026-07-09": `Letzter Tag für mich schon wieder. Also morgen ist Abreise, keine Ahnung wann wir fahren wollen oder so. Zumindest gerade noch nicht. Bin auch gespannt ob ich wieder die ganze Distanz alleine fahre. Aber war schon witzig eigentlich bei der Anreise. Ich muss übrigens echt aufhören Liebeslieder zu hören. Will einfach alles mit dir machen. Halt einfach alles, einfach du. Und vermiss dich nur mehr und mehr. Ich liebe dich halt einfach soooo sehr. Dein Basti ♥`,
    "2026-07-11": `Bin wieder zuhause. Ach vermiss ich dich. Und weißt du wie schlimm du eigentlich bist? Also so gestern Abend. Hab vorhin gerade bissi gelesen und das ist ja soooo schlimm wie süß du bist. Und wie du dich kümmerst. Und auch wie man sieht dass ich dir wichtig bin. Das ist sooo schön. Ich hab dich so lieb, danke. Danke dass du meine Paula bist und dass ich dir so wichtig sein darf. Hab dich liiieb. Dein Basti ♥`,
    "2026-07-12": `Sonntag. Ist jetzt schon weniger als eine Woche bis wir uns wieder sehen. Ich freu mich schon soooo. Ging ja sicher schon schnell bis jetzt. Und wird noch schneller werden. Und trotzdem weiß ich wie sehr ich es vermisse einfach in deinen Armen zu sein. Einfach da bei dir, wo ich mich so unendlich wohl fühle. Wo mir egal ist was alles passier und einfach nur du meine Paula bist. Ich hab dich so lieb. Dein Basti ♥`,
    "2026-07-13": `Uiuiui. Hatte heute Reihungstest. Ist ja sicher ganz gut gelaufen. Ich kann das ja eh schon alles oder so. Trotzdem bin ich unglaublich nervös. Ur ungewohnt. Ich bin eigentlich fast nie nervös vor Tests. Vielleicht liegt es ja einfach daran, dass ich auf Paula-Entzug bin. Ich vermiss dich so schlimm. Und freu mich sooo sehr dich wieder zu sehen. Hab dich sooooo unfassbar lieb. Dein Basti ♥`,
    "2026-07-14": `Hiiii. Wie gehts so? Sicher wieder ein anstrengender Tag und so. Aber du schaffst das. Und morgen, hihi. Morgen wird toll. Da bin ja ich da. Und ich glaub du magst mich. Also nur theoretisch. Freu mich schon soooooo sehr auf dich. Ist viel zu lang gewesen dass ich dich nicht gesehen habe. Und dann ist es ja auch schon bald geschafft. Sind ja nur noch ein paar Tage bis Samstag Abend. Ich hab dich liiiieb. Und freu mich soooo auf dich. Dein Basti ♥`,
    "2026-07-15": `Haaaalllooo. Ich bin da. Werde da sein? Bin da gewesen? Egaaaal. Aber bin bei diiir. Ach ist das schln, es macht mich soooo glücklich, dass ich dich bisschen früher zu sehen. Ich hab dich soooo unendlich vermisst. Mal schauen was wir machen. Aber mit dir ist es sicher immer schön. Mit dir ist ja alles immer schön. Weil du halt einfach schön bist. Ich hab dich soooo lieb. Und jetzt ist es auch nicht mehr lang bis wir uns wieder sehen. Also nochmal. Dein Basti ♥`
};
